/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs221final;

import java.sql.Timestamp;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Michael Fink
 */
public class Graphic extends javax.swing.JFrame {
Magician mage;
Holiday holi;
    /**
     * Creates new form MainGUI
     */
    public Graphic() {
         mage= new Magician();
     holi= new Holiday();

        WaitList.importInstances(holi);
        Booking.importInstances(mage, holi);
           
   
        initComponents();
             updateHolidays();
             updateMagicians();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bookTP = new javax.swing.JTabbedPane();
        statusTP = new javax.swing.JPanel();
        statusCB = new javax.swing.JComboBox();
        magicianCB = new javax.swing.JComboBox();
        holidayCB = new javax.swing.JComboBox();
        statusB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BookTP = new javax.swing.JPanel();
        bookB = new javax.swing.JButton();
        nameTB = new javax.swing.JTextField();
        holidayBookCB = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cancelTP = new javax.swing.JPanel();
        cancelHolidayB = new javax.swing.JButton();
        cancelTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cancelCB = new javax.swing.JComboBox();
        addDropTP = new javax.swing.JPanel();
        addTB = new javax.swing.JTextField();
        addMagicianB = new javax.swing.JButton();
        addHolidayB = new javax.swing.JButton();
        dropCB = new javax.swing.JComboBox();
        dropMagicianB = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookTP.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                bookTPFocusGained(evt);
            }
        });

        statusCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Holiday", "Magician", "Wait List" }));

        magicianCB.setModel(new javax.swing.DefaultComboBoxModel(mage.getItems()));

        holidayCB.setModel(new javax.swing.DefaultComboBoxModel(holi.getItems()));

        statusB.setText("Status");
        statusB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                statusBActionPerformed(evt);
            }
        });

        jLabel4.setText("Choose Action: ");

        jLabel5.setText("Magician: ");

        jLabel6.setText("Holiday/Waitlist:");

        javax.swing.GroupLayout statusTPLayout = new javax.swing.GroupLayout(statusTP);
        statusTP.setLayout(statusTPLayout);
        statusTPLayout.setHorizontalGroup(
            statusTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusTPLayout.createSequentialGroup()
                        .addGroup(statusTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(statusTPLayout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusTPLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(statusTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(holidayCB, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(magicianCB, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addComponent(statusB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        statusTPLayout.setVerticalGroup(
            statusTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusTPLayout.createSequentialGroup()
                .addGroup(statusTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusTPLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(statusTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(holidayCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(statusTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(magicianCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(statusTPLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(statusTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(statusB)
                .addContainerGap())
        );

        bookTP.addTab("Status", statusTP);

        bookB.setText("Book");
        bookB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bookBActionPerformed(evt);
            }
        });

        nameTB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nameTBActionPerformed(evt);
            }
        });

        holidayBookCB.setModel(new javax.swing.DefaultComboBoxModel(holi.getItems()));

        jLabel3.setText("Customer Name: ");

        javax.swing.GroupLayout BookTPLayout = new javax.swing.GroupLayout(BookTP);
        BookTP.setLayout(BookTPLayout);
        BookTPLayout.setHorizontalGroup(
            BookTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookTPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BookTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookB, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BookTPLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTB, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(holidayBookCB, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        BookTPLayout.setVerticalGroup(
            BookTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookTPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BookTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(holidayBookCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookB, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        bookTP.addTab("Book", BookTP);

        cancelHolidayB.setText("Cancel Customer Holiday");
        cancelHolidayB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelHolidayBActionPerformed(evt);
            }
        });

        cancelTF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelTFActionPerformed(evt);
            }
        });

        jLabel2.setText("Customer Name:");

        cancelCB.setModel(new javax.swing.DefaultComboBoxModel(holi.getItems())
        );

        javax.swing.GroupLayout cancelTPLayout = new javax.swing.GroupLayout(cancelTP);
        cancelTP.setLayout(cancelTPLayout);
        cancelTPLayout.setHorizontalGroup(
            cancelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelTPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelCB, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelTPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelHolidayB, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cancelTPLayout.setVerticalGroup(
            cancelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelTPLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(cancelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cancelCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelHolidayB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bookTP.addTab("Cancel", cancelTP);

        addMagicianB.setText("Add Magician");
        addMagicianB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addMagicianBActionPerformed(evt);
            }
        });

        addHolidayB.setText("Add Holiday");
        addHolidayB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addHolidayBActionPerformed(evt);
            }
        });

        dropCB.setModel(new javax.swing.DefaultComboBoxModel(mage.getItems()));

        dropMagicianB.setText("Drop Magician");
        dropMagicianB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dropMagicianBActionPerformed(evt);
            }
        });

        jLabel1.setText("Name to add:");

        javax.swing.GroupLayout addDropTPLayout = new javax.swing.GroupLayout(addDropTP);
        addDropTP.setLayout(addDropTPLayout);
        addDropTPLayout.setHorizontalGroup(
            addDropTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDropTPLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(dropCB, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dropMagicianB, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(addDropTPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(addDropTPLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(addDropTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDropTPLayout.createSequentialGroup()
                        .addComponent(addMagicianB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addHolidayB))
                    .addComponent(addTB, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addDropTPLayout.setVerticalGroup(
            addDropTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDropTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDropTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDropTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMagicianB)
                    .addComponent(addHolidayB))
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDropTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropMagicianB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bookTP.addTab("Add/Drop", addDropTP);

        outputTA.setEditable(false);
        outputTA.setColumns(20);
        outputTA.setLineWrap(true);
        outputTA.setCaretPosition(0);
        outputTA.setRows(5);
        jScrollPane1.setViewportView(outputTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookTP, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bookTP, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        bookTP.getAccessibleContext().setAccessibleName("tab");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statusBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBActionPerformed
        // TODO add your handling code here:
        //good to go
        
        String item = statusCB.getSelectedItem().toString();
        
        if(item.equals("Wait List"))
        {
            outputTA.setText(WaitList.read(holidayCB.getSelectedItem().toString())+"\n"+outputTA.getText());
        }
        else if(item.equals("Magician"))
        {
            outputTA.setText(mage.getStatus(magicianCB.getSelectedItem().toString())+"\n"+outputTA.getText());
        }
        else if(item.equals("Holiday"))
        {
            outputTA.setText(holi.getStatus(holidayCB.getSelectedItem().toString())+"\n"+outputTA.getText());
        }
        else
        {
            outputTA.setText("Error"+"\n"+outputTA.getText());
        } outputTA.setCaretPosition(0);
    }//GEN-LAST:event_statusBActionPerformed

    private void cancelHolidayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelHolidayBActionPerformed
        if(cancelTF.getText().equals(""))
        {  outputTA.setText( "please enter a name\n"+outputTA.getText());
         outputTA.setCaretPosition(0);
        }else{
         outputTA.setText(Booking.cancelHoliday(cancelCB.getSelectedItem().toString(), cancelTF.getText())+"\n"+outputTA.getText());
   outputTA.setCaretPosition(0);
        }
    }//GEN-LAST:event_cancelHolidayBActionPerformed

    private void addMagicianBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMagicianBActionPerformed
        // TODO add your handling code here:
        //good to go?
              if(addTB.getText().equals(""))
            outputTA.setText( "please enter a name\n"+outputTA.getText());
              else
        outputTA.setText("Magician "+addTB.getText()+" was added to the database. \n"+mage.add(addTB.getText())+outputTA.getText());
         outputTA.setCaretPosition(0);
         updateMagicians();
        
    }//GEN-LAST:event_addMagicianBActionPerformed

    private void addHolidayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHolidayBActionPerformed
        // TODO add your handling code here:
        //good to go!
              if(addTB.getText().equals(""))
            outputTA.setText( "please enter a name\n"+outputTA.getText());
              else{
        holi.add(addTB.getText());
        updateHolidays();
        outputTA.setText("Holiday "+addTB.getText()+" was added to the database."+"\n"+outputTA.getText());
         outputTA.setCaretPosition(0);
    }//GEN-LAST:event_addHolidayBActionPerformed
    }
    
    
    
    private void dropMagicianBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropMagicianBActionPerformed
        // TODO add your handling code here:
        //good to go
          outputTA.setText("Magician "+dropCB.getSelectedItem().toString()+" was removed from the database."+"\n"+outputTA.getText());
      outputTA.setText( mage.drop(dropCB.getSelectedItem().toString())+"\n"+outputTA.getText());
       outputTA.setCaretPosition(0);
        updateMagicians();
        
     
    }//GEN-LAST:event_dropMagicianBActionPerformed

    private void bookTPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookTPFocusGained
        // TODO add your handling code here:
        updateHolidays();
        updateMagicians();
        
    }//GEN-LAST:event_bookTPFocusGained

    private void bookBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bookBActionPerformed
    {//GEN-HEADEREND:event_bookBActionPerformed
        // TODO add your handling code here:
        if(nameTB.getText().equals(""))
            outputTA.setText( "please enter a name\n"+outputTA.getText());
              else{
        outputTA.setText(Booking.book(holi.getID(holidayBookCB.getSelectedItem().toString()),  nameTB.getText())+"\n"+outputTA.getText());
        outputTA.setCaretPosition(0);
        }
    }//GEN-LAST:event_bookBActionPerformed

    private void cancelTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelTFActionPerformed
    {//GEN-HEADEREND:event_cancelTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelTFActionPerformed

    private void nameTBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nameTBActionPerformed
    {//GEN-HEADEREND:event_nameTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTBActionPerformed

    private void updateMagicians()
    {
        dropCB.setModel(new DefaultComboBoxModel(mage.getItems()));
        magicianCB.setModel(new DefaultComboBoxModel(mage.getItems()));
        
    }
    
    private void updateHolidays()
    {
        holidayCB.setModel(new DefaultComboBoxModel(holi.getItems()));
        cancelCB.setModel(new DefaultComboBoxModel(holi.getItems()));
        holidayBookCB.setModel(new DefaultComboBoxModel(holi.getItems()));
      
    }
    
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookTP;
    private javax.swing.JPanel addDropTP;
    private javax.swing.JButton addHolidayB;
    private javax.swing.JButton addMagicianB;
    private javax.swing.JTextField addTB;
    private javax.swing.JButton bookB;
    private javax.swing.JTabbedPane bookTP;
    private javax.swing.JComboBox cancelCB;
    private javax.swing.JButton cancelHolidayB;
    private javax.swing.JTextField cancelTF;
    private javax.swing.JPanel cancelTP;
    private javax.swing.JComboBox dropCB;
    private javax.swing.JButton dropMagicianB;
    private javax.swing.JComboBox holidayBookCB;
    private javax.swing.JComboBox holidayCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox magicianCB;
    private javax.swing.JTextField nameTB;
    private javax.swing.JTextArea outputTA;
    private javax.swing.JButton statusB;
    private javax.swing.JComboBox statusCB;
    private javax.swing.JPanel statusTP;
    // End of variables declaration//GEN-END:variables

}
